# Generated by Django 6.0.7 on 2026-07-31 04:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0005_seed_city_identities_and_enforce_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must be 3–30 characters using letters, numbers, underscores, or periods; it must begin and end with a letter or number and cannot contain consecutive periods.",
                                regex="^(?!.*\\.\\.)[a-z0-9][a-z0-9_.]{1,28}[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                (
                    "recovery_username",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("display_name", models.CharField(max_length=50)),
                ("bio", models.CharField(blank=True, max_length=150, null=True)),
                ("avatar", models.URLField(blank=True, max_length=2048, null=True)),
                ("is_private", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("pending_deletion", "Pending deletion"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deletion_due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "home_city",
                    models.ForeignKey(
                        blank=True,
                        db_column="home_city_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="catalog.city",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "DANCED_USER",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "active"), ("username__isnull", False)),
                            models.Q(
                                ("status__in", ("deactivated", "pending_deletion")),
                                ("username__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_user_status_username",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deletion_due_at__isnull", False),
                                ("status", "pending_deletion"),
                            ),
                            models.Q(
                                models.Q(("status", "pending_deletion"), _negated=True),
                                ("deletion_due_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_user_status_deletion_due",
                    ),
                ],
            },
            managers=[
                ("objects", users.models.DancedUserManager()),
            ],
        ),
    ]
