# Generated by Django 6.0.7 on 2026-07-31 04:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_city_identities_and_enforce_cascade"),
        ("users", "0002_remove_legacy_auth_user_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("rated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="diary_entries",
                        to="catalog.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIARY_ENTRY",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event"), name="uq_diary_user_event"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("rated_at__isnull", True), ("rating__isnull", True)
                            ),
                            models.Q(
                                ("rated_at__isnull", False), ("rating__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="ck_diary_rating_rated_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__isnull", True),
                            (
                                "rating__in",
                                (
                                    Decimal("0.5"),
                                    Decimal("1.0"),
                                    Decimal("1.5"),
                                    Decimal("2.0"),
                                    Decimal("2.5"),
                                    Decimal("3.0"),
                                    Decimal("3.5"),
                                    Decimal("4.0"),
                                    Decimal("4.5"),
                                    Decimal("5.0"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="ck_diary_rating_half_star",
                    ),
                ],
            },
        ),
    ]
