# Generated by Django 6.0.7 on 2026-07-31 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_enforce_review_database_cascades"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "follower_id",
                        "followee_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "followee",
                    models.ForeignKey(
                        db_column="followee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        db_column="follower_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FOLLOW",
                "indexes": [
                    models.Index(
                        fields=["followee", "status"], name="ix_follow_followee_status"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("followee")), _negated=True
                        ),
                        name="ck_follow_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_at__isnull", False), ("status", "approved")
                            ),
                            models.Q(
                                ("approved_at__isnull", True), ("status", "pending")
                            ),
                            _connector="OR",
                        ),
                        name="ck_follow_status_approved_at",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("review_like", "Review like"),
                            ("follow", "Follow"),
                            ("follow_request", "Follow request"),
                            ("request_accepted", "Request accepted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        db_column="actor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        db_column="recipient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        db_column="review_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.review",
                    ),
                ),
            ],
            options={
                "db_table": "NOTIFICATION",
                "indexes": [
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="ix_notif_recipient_created",
                    ),
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="ix_notification_recipient_read",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recipient", models.F("actor")), _negated=True
                        ),
                        name="ck_notification_actor_recipient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("review__isnull", False), ("type", "review_like")
                            ),
                            models.Q(
                                models.Q(("type", "review_like"), _negated=True),
                                ("review__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_notification_type_review",
                    ),
                ],
            },
        ),
    ]
