# Generated by Django 6.0.7 on 2026-07-31 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_city_identities_and_enforce_cascade"),
        ("users", "0011_correct_home_city_restrict"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteArtist",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "artist_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField()),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="favorited_by",
                        to="catalog.artist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_artists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FAVORITE_ARTIST",
            },
        ),
        migrations.CreateModel(
            name="FavoriteEvent",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "event_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="favorited_by",
                        to="catalog.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FAVORITE_EVENT",
            },
        ),
        migrations.CreateModel(
            name="FavoriteVenue",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "venue_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        db_column="venue_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="favorited_by",
                        to="catalog.venue",
                    ),
                ),
            ],
            options={
                "db_table": "FAVORITE_VENUE",
            },
        ),
    ]
