# Generated by Django 6.0.7 on 2026-08-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_enforce_favorite_user_cascades"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email verification"),
                            ("password_reset", "Password reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("sent_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ACCOUNT_CODE",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "purpose"), name="uq_account_code_user_purpose"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("failed_attempts__lte", 5)),
                        name="ck_account_code_attempts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("sent_at"))),
                        name="ck_account_code_expiry",
                    ),
                ],
            },
        ),
    ]
