# Generated by Django 6.0.7 on 2026-07-30 19:54

from django.db import migrations


CASCADE_FOREIGN_KEYS = (
    ("EVENT_ARTIST", "event_id", "EVENT", "id", "fk_event_artist_event"),
    ("EVENT_IDENTITY", "event_id", "EVENT", "id", "fk_event_identity_event"),
    ("VENUE_IDENTITY", "venue_id", "VENUE", "id", "fk_venue_identity_venue"),
    ("ARTIST_IDENTITY", "artist_id", "ARTIST", "id", "fk_artist_identity_artist"),
)


def _replace_foreign_key(
    schema_editor,
    *,
    table,
    column,
    target_table,
    target_column,
    new_name,
    cascade,
):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table)

    matches = [
        name
        for name, details in constraints.items()
        if details["columns"] == [column]
        and details["foreign_key"] == (target_table, target_column)
    ]
    if len(matches) != 1:
        raise RuntimeError(
            f"Expected exactly one FK {table}.{column} -> "
            f"{target_table}.{target_column}; found {matches!r}"
        )

    quote = schema_editor.quote_name
    delete_clause = " ON DELETE CASCADE" if cascade else ""
    schema_editor.execute(
        f"ALTER TABLE {quote(table)} "
        f"DROP FOREIGN KEY {quote(matches[0])}, "
        f"ADD CONSTRAINT {quote(new_name)} "
        f"FOREIGN KEY ({quote(column)}) "
        f"REFERENCES {quote(target_table)} ({quote(target_column)})"
        f"{delete_clause}"
    )


def enforce_database_cascades(apps, schema_editor):
    for table, column, target_table, target_column, name in CASCADE_FOREIGN_KEYS:
        _replace_foreign_key(
            schema_editor,
            table=table,
            column=column,
            target_table=target_table,
            target_column=target_column,
            new_name=name,
            cascade=True,
        )


def restore_restrictive_foreign_keys(apps, schema_editor):
    for table, column, target_table, target_column, name in CASCADE_FOREIGN_KEYS:
        _replace_foreign_key(
            schema_editor,
            table=table,
            column=column,
            target_table=target_table,
            target_column=target_column,
            new_name=f"{name}_restrict",
            cascade=False,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalog", "0002_seed_v1_cities"),
    ]

    operations = [
        migrations.RunPython(
            enforce_database_cascades,
            restore_restrictive_foreign_keys,
        ),
    ]
