# Generated by Django 6.0.7 on 2026-07-30 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_enforce_database_cascades"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ra", "Resident Advisor")], max_length=50
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        db_column="city_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="catalog.city",
                    ),
                ),
            ],
            options={
                "db_table": "CITY_IDENTITY",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="uq_city_identity_external"
                    ),
                    models.UniqueConstraint(
                        fields=("city", "source"),
                        name="uq_city_identity_canonical_source",
                    ),
                ],
            },
        ),
    ]
