# Generated by Django 6.0.7 on 2026-07-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("nightly", "Nightly"),
                            ("backfill", "Backfill"),
                            ("replay", "Replay"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("crashed", "Crashed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("seeds_attempted", models.IntegerField(default=0)),
                ("seeds_failed", models.IntegerField(default=0)),
                ("events_upserted", models.IntegerField(default=0)),
                ("events_quarantined", models.IntegerField(default=0)),
                ("events_dropped", models.IntegerField(default=0)),
                ("error_summary", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "SYNC_RUN",
            },
        ),
        migrations.CreateModel(
            name="TrackedSourcePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ra", "Resident Advisor")], max_length=50
                    ),
                ),
                ("area_ref", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "TRACKED_SOURCE_PAGE",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "area_ref"), name="uq_tracked_source_area"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawIngest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateField(blank=True, null=True)),
                ("window_end", models.DateField(blank=True, null=True)),
                ("page_number", models.IntegerField()),
                ("page_size", models.IntegerField()),
                ("response_body", models.TextField(blank=True, null=True)),
                ("http_status", models.SmallIntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="raw_ingests",
                        to="ingestion.syncrun",
                    ),
                ),
                (
                    "seed",
                    models.ForeignKey(
                        db_column="seed_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="raw_ingests",
                        to="ingestion.trackedsourcepage",
                    ),
                ),
            ],
            options={
                "db_table": "RAW_INGEST",
            },
        ),
        migrations.CreateModel(
            name="RejectedIngest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_ref", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("OUT_OF_SCOPE", "Out of scope"),
                            ("NO_ARTIST", "No artist"),
                            ("EMPTY_TITLE", "Empty title"),
                            ("BAD_DATE", "Bad date"),
                            ("PARSE_FAILURE", "Event-level parse failure"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.TextField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField()),
                (
                    "raw_ingest",
                    models.ForeignKey(
                        db_column="raw_ingest_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rejections",
                        to="ingestion.rawingest",
                    ),
                ),
            ],
            options={
                "db_table": "REJECTED_INGEST",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raw_ingest", "entity_ref"),
                        name="uq_rejection_payload_entity",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rawingest",
            index=models.Index(fields=["run"], name="ix_raw_ingest_run"),
        ),
        migrations.AddIndex(
            model_name="rawingest",
            index=models.Index(
                fields=["seed", "fetched_at"], name="ix_raw_ingest_seed_fetched"
            ),
        ),
    ]
