# Generated by Django 6.0.7 on 2026-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rawingest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_status__in", ["pending", "processed", "failed"])
                ),
                name="ck_raw_processing_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="rejectedingest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason__in",
                        [
                            "OUT_OF_SCOPE",
                            "NO_ARTIST",
                            "EMPTY_TITLE",
                            "BAD_DATE",
                            "PARSE_FAILURE",
                        ],
                    )
                ),
                name="ck_rejection_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_type__in", ["nightly", "backfill", "replay"])),
                name="ck_sync_run_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "completed", "crashed"])),
                name="ck_sync_run_status",
            ),
        ),
    ]
