# Generated by Django 6.0.7 on 2026-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_rawingest_ck_raw_processing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectedingest",
            name="entity_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rejectedingest",
            name="entity_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="rejectedingest",
            constraint=models.UniqueConstraint(
                fields=("raw_ingest", "entity_index"), name="uq_rejection_payload_index"
            ),
        ),
        migrations.RemoveConstraint(
            model_name="rejectedingest",
            name="uq_rejection_payload_entity",
        ),
    ]
