# Generated by Django 6.0.7 on 2026-07-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "db_table": "ARTIST",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("region_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("timezone", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "CITY",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "region_code", "name"),
                        name="uq_city_country_region_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        db_column="city_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="venues",
                        to="catalog.city",
                    ),
                ),
            ],
            options={
                "db_table": "VENUE",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unverified", "Unverified"),
                            ("hidden", "Hidden"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        db_column="venue_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="catalog.venue",
                    ),
                ),
            ],
            options={
                "db_table": "EVENT",
            },
        ),
        migrations.CreateModel(
            name="VenueIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ra", "Resident Advisor")], max_length=50
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                (
                    "venue",
                    models.ForeignKey(
                        db_column="venue_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="catalog.venue",
                    ),
                ),
            ],
            options={
                "db_table": "VENUE_IDENTITY",
            },
        ),
        migrations.CreateModel(
            name="ArtistIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ra", "Resident Advisor")], max_length=50
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="catalog.artist",
                    ),
                ),
            ],
            options={
                "db_table": "ARTIST_IDENTITY",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="uq_artist_identity_external",
                    ),
                    models.UniqueConstraint(
                        fields=("artist", "source"),
                        name="uq_artist_identity_canonical_source",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="event_artists",
                        to="catalog.artist",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artists",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "db_table": "EVENT_ARTIST",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "artist"), name="uq_event_artist_pair"
                    ),
                    models.UniqueConstraint(
                        fields=("event", "position"), name="uq_event_artist_position"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ra", "Resident Advisor")], max_length=50
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("misses", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "db_table": "EVENT_IDENTITY",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="uq_event_identity_external",
                    ),
                    models.UniqueConstraint(
                        fields=("event", "source"),
                        name="uq_event_identity_canonical_source",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "event_date"], name="ix_event_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["venue", "event_date"], name="ix_event_venue_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "unverified", "hidden"])),
                name="ck_event_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="venueidentity",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"), name="uq_venue_identity_external"
            ),
        ),
        migrations.AddConstraint(
            model_name="venueidentity",
            constraint=models.UniqueConstraint(
                fields=("venue", "source"), name="uq_venue_identity_canonical_source"
            ),
        ),
    ]
