# Generated by Django 6.0.7 on 2026-07-30 19:53

from django.db import migrations


V1_CITIES = (
    {
        "name": "New York City",
        "region_code": "NY",
        "region_name": "New York",
        "country_code": "US",
        "timezone": "America/New_York",
    },
    {
        "name": "Boston",
        "region_code": "MA",
        "region_name": "Massachusetts",
        "country_code": "US",
        "timezone": "America/New_York",
    },
)


def seed_v1_cities(apps, schema_editor):
    City = apps.get_model("catalog", "City")
    for city in V1_CITIES:
        City.objects.update_or_create(
            country_code=city["country_code"],
            region_code=city["region_code"],
            name=city["name"],
            defaults={
                "region_name": city["region_name"],
                "timezone": city["timezone"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_v1_cities, migrations.RunPython.noop),
    ]
