# Generated by Django 6.0.7 on 2026-07-30 20:22

from django.db import migrations


CITY_MAPPINGS = (
    {
        "country_code": "US",
        "region_code": "NY",
        "name": "New York City",
        "source": "ra",
        "source_id": "8",
    },
    {
        "country_code": "US",
        "region_code": "MA",
        "name": "Boston",
        "source": "ra",
        "source_id": "530",
    },
)


def _replace_city_foreign_key(schema_editor, *, cascade):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, "CITY_IDENTITY")

    matches = [
        name
        for name, details in constraints.items()
        if details["columns"] == ["city_id"]
        and details["foreign_key"] == ("CITY", "id")
    ]
    if len(matches) != 1:
        raise RuntimeError(
            "Expected exactly one FK CITY_IDENTITY.city_id -> CITY.id; "
            f"found {matches!r}"
        )

    quote = schema_editor.quote_name
    new_name = (
        "fk_city_identity_city"
        if cascade
        else "fk_city_identity_city_restrict"
    )
    delete_clause = " ON DELETE CASCADE" if cascade else ""
    schema_editor.execute(
        f"ALTER TABLE {quote('CITY_IDENTITY')} "
        f"DROP FOREIGN KEY {quote(matches[0])}, "
        f"ADD CONSTRAINT {quote(new_name)} "
        f"FOREIGN KEY ({quote('city_id')}) "
        f"REFERENCES {quote('CITY')} ({quote('id')})"
        f"{delete_clause}"
    )


def seed_city_identities_and_enforce_cascade(apps, schema_editor):
    City = apps.get_model("catalog", "City")
    CityIdentity = apps.get_model("catalog", "CityIdentity")

    for mapping in CITY_MAPPINGS:
        try:
            city = City.objects.get(
                country_code=mapping["country_code"],
                region_code=mapping["region_code"],
                name=mapping["name"],
            )
        except City.DoesNotExist as exc:
            raise RuntimeError(
                "CITY_IDENTITY seed requires its canonical CITY row: "
                f"{mapping['name']}, {mapping['region_code']}"
            ) from exc

        CityIdentity.objects.update_or_create(
            source=mapping["source"],
            source_id=mapping["source_id"],
            defaults={"city": city},
        )

    _replace_city_foreign_key(schema_editor, cascade=True)


def remove_city_identities_and_restore_restrict(apps, schema_editor):
    _replace_city_foreign_key(schema_editor, cascade=False)
    CityIdentity = apps.get_model("catalog", "CityIdentity")
    for mapping in CITY_MAPPINGS:
        CityIdentity.objects.filter(
            source=mapping["source"],
            source_id=mapping["source_id"],
        ).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalog", "0004_cityidentity"),
    ]

    operations = [
        migrations.RunPython(
            seed_city_identities_and_enforce_cascade,
            remove_city_identities_and_restore_restrict,
        ),
    ]
