export const REMEDIATION_VIEWPORTS = [
  { name: "mobile-chrome-320", width: 320, height: 720 },
  { name: "mobile-chrome-390", width: 390, height: 844 },
  { name: "mobile-chrome-767", width: 767, height: 900 },
  { name: "desktop-chrome-768", width: 768, height: 900 },
  { name: "desktop-chrome-1280", width: 1280, height: 900 },
  { name: "wide-desktop-1440", width: 1440, height: 1000 },
];

export const REMEDIATION_STATE_FAMILIES = [
  "empty",
  "sparse",
  "normal",
  "dense-extreme",
  "media-present",
  "media-absent",
  "media-failed",
  "initial-loading",
  "initial-error",
  "continuation-error",
  "mutation-error",
  "hover",
  "keyboard-focus",
  "selected",
  "disabled",
  "open-dismiss",
  "text-enlargement-200",
];

export const REMEDIATION_ROUTE_CLASSES = [
  { id: "R00", surface: "Global shell", routes: ["all routes"] },
  { id: "R01", surface: "Landing resolver", routes: ["/"] },
  { id: "R02", surface: "Discover", routes: ["/discover"] },
  { id: "R03", surface: "Search", routes: ["/search"] },
  { id: "R04", surface: "Home", routes: ["/home"] },
  { id: "R05", surface: "Activity", routes: ["/activity"] },
  { id: "R06", surface: "Profile", routes: ["/u/:username", "/u/:username/reviews"] },
  { id: "R07", surface: "Edit profile", routes: ["/settings/profile"] },
  { id: "R08", surface: "Event", routes: ["/e/:eventKey", "/events/:eventKey"] },
  { id: "R09", surface: "Venue", routes: ["/v/:venueKey", "/venues/:venueKey"] },
  { id: "R10", surface: "Artist", routes: ["/a/:artistKey", "/artists/:artistKey"] },
  { id: "R11", surface: "Register", routes: ["/register"] },
  { id: "R12", surface: "Login", routes: ["/login"] },
  { id: "R13", surface: "Verify email", routes: ["/verify-email"] },
  { id: "R14", surface: "Password-reset request", routes: ["/reset-password"] },
  { id: "R15", surface: "Password-reset form", routes: ["/reset-password/confirm"] },
  { id: "R16", surface: "Legacy Been", routes: ["/been"] },
  { id: "R17", surface: "Global and entity not found", routes: ["unmatched and missing entity paths"] },
];
