# Generated by Django 6.0.7 on 2026-07-31 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_enforce_diary_user_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=1000)),
                ("published_at", models.DateTimeField()),
                (
                    "entry",
                    models.OneToOneField(
                        db_column="entry_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="users.diaryentry",
                    ),
                ),
            ],
            options={
                "db_table": "REVIEW",
            },
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "review_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="users.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "REVIEW_LIKE",
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("body__regex", "^ *$"), _negated=True),
                name="ck_review_body_nonblank",
            ),
        ),
    ]
