# Generated by Django 6.0.7 on 2026-07-31 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_city_identities_and_enforce_cascade"),
        ("users", "0008_enforce_social_database_cascades"),
    ]

    operations = [
        migrations.CreateModel(
            name="WillBeThere",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "event_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="will_be_there_entries",
                        to="catalog.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="will_be_there_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "WILL_BE_THERE",
            },
        ),
    ]
