# Generated by Django 6.0.7 on 2026-07-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_city_identities_and_enforce_cascade"),
        ("users", "0010_enforce_wbt_user_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="home_city",
            field=models.ForeignKey(
                blank=True,
                db_column="home_city_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="catalog.city",
            ),
        ),
    ]
