# Generated by Django 6.0.7 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_mark_semantic_event_aliases"),
        ("users", "0017_request_throttle"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                db_column="event_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="catalog.event",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("review_like", "Review like"),
                    ("follow", "Follow"),
                    ("follow_request", "Follow request"),
                    ("request_accepted", "Request accepted"),
                    ("will_be_there", "Will be there"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="ck_notification_type_review",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        type="review_like",
                        review__isnull=False,
                        event__isnull=True,
                    )
                    | models.Q(
                        type="will_be_there",
                        review__isnull=True,
                        event__isnull=False,
                    )
                    | (
                        ~models.Q(type__in=("review_like", "will_be_there"))
                        & models.Q(review__isnull=True)
                        & models.Q(event__isnull=True)
                    )
                ),
                name="ck_notification_type_target",
            ),
        ),
    ]
